version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.3-fpm-node
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            cp .env.testing .env
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo -E docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath
      - run: sudo docker-php-ext-enable xdebug

      # composer cache
      - restore_cache:
          keys:
          # "composer.lock" can be used if it is committed to the repo
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      # node cache
      - restore_cache:
          keys:
            - node-v3-{{ checksum "package.json" }}
            - node-v3-
      - run: yarn install
      - save_cache:
          key: node-v3-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn
      - run: composer dump-autoload
      # prepare the database
      - run: php vendor/bin/artisan key:generate
      - run: ./vendor/bin/phpcs src/
      - run:
          name: Run App Feature Tests
          command: ./vendor/bin/phpunit --testsuite Feature
      - run: ls -lah ./
      - codecov/upload:
          file: ./phpunit.coverage.xml
      - run:
          name: Run App Unit Tests
          command: ./vendor/bin/phpunit --testsuite Unit
      - run: ls -lah ./
      - codecov/upload:
          file: ./phpunit.coverage.xml
